### ISSUE TITLE
Make the wrapped load function return a proper cheerio object

### ISSUE THREAD

**Issue by watson** [watson/cheerio-advanced-selectors#2]
At the moment the result returned from the `.load()` function isn't a cheerio object but just a function taking a `selector` and optionally a `context` and a `root`. This means that you cannot call the normal cheerio functions on it - I.e. the following will **not** work:

``` js
var cheerio = require('cheerio-advanced-selectors').wrap(require('cheerio'))
var $ = cheerio.load('<p>foo</p>')
$.html() // BREAKS!
```

It would be nice if the result returned from `.load()` was a proper cheerio object, but still wrapped with the enhancements of cheerio-advanced-selectors.

**Comment by addnab** [comment]
How about this?

``` js
var merge = require('lodash.merge')

CheerioAdv.load = function () {
  var $ = Cheerio.load.apply(Cheerio, arguments)
  var $adv = function (selector, context, root) {
    if (typeof selector === 'string') return exports.find($, selector, context, root)
    return $.apply(Cheerio, arguments)
  }
  $adv.prototype = Object.create($.prototype)
  merge($adv, $)
  return $adv
}
```

**Comment by watson** [comment]
Are there any downsides to overwriting the prototype like this? Never tried to do that before...

**Comment by addnab** [comment]
I was just trying to mimic the `initialize` variable [here](https://github.com/cheeriojs/cheerio/blob/master/lib/static.js#L24). 
It appears overwriting the prototype would help it behave more like a [cheerio](https://github.com/cheeriojs/cheerio/blob/master/lib/cheerio.js) object.

A more apt solution would probably be something like - 

``` js
var merge = require('lodash.merge')

CheerioAdv.load = function () {
  var $ = Cheerio.load.apply(Cheerio, arguments)
  var $adv = function (selector, context, r, opts) {
    if (!(this instanceof $adv)) {
      return new $adv(selector, context, r, opts);
    }
    if (typeof selector === 'string') return exports.find($, selector, context, root)
    return $.apply(Cheerio, arguments)
  }
  $adv.prototype = Object.create($.prototype)
  $adv.prototype.constructor = $
  merge($adv, $)
  $adv.load = CheerioAdv.load
  return $adv
}
```

If you don't see any problems with this, I could help and try to test this change with cheerio's actual test cases.

**Comment by evandrix** [comment]
really needed this to return a `cheerio` object, especially for `$.html` (a.k.a. `outerHTML()`), while preserving the advanced selector functions capability, so i achieved this by forwarding `Cheerio` object functions instead:
```const Cheerio = require("cheerio");
const CheerioAdv = require("cheerio-advanced-selectors");
const cheerio = CheerioAdv.wrap(Cheerio);
cheerio.load=function(){const $=Cheerio.load.apply(Cheerio,arguments);const fn=function(selector,context,root){if(typeof selector==="string"){return CheerioAdv.find($,selector,context,root)}return $.apply(Cheerio,arguments)};for(let prop in Cheerio){if(prop==="load"||typeof Cheerio[prop]!=="function"){continue}fn[prop]=function(){return Cheerio[prop].apply($,arguments)}}return fn};```

**Comment by watson** [comment]
This have now been fixed in v2.x

**Comment by watson** [comment]
The only breaking change between 1.x and 2.x is that I stopped testing on older versions of Node.js (older than v4), so there's no longer any guarantee that this module will work on those versions.
